/**
 * Report library.
 *
 * Reports are generated by the API from live data (permit register, harvesting
 * register, revenue, cases…), stored as files and listed here. Every row is real:
 * the download streams the stored file with the caller's token, "share" notifies
 * the services the report concerns, and delete removes the record and its file.
 */
import React, { useMemo, useState } from 'react';
import { Pressable, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { ApiError } from '../../../src/api/client';
import type { Report, ReportFormat, ReportStatus, ReportType } from '../../../src/api/types';
import { useDeleteReport, useReportStatistics, useReports, useSendReport } from '../../../src/api/queries';
import { useAuth } from '../../../src/auth/AuthProvider';
import { downloadAuthenticatedFile } from '../../../src/lib/file-download';
import { formatDateTime, formatNumber, formatRelative, reportStatusLabel, reportTypeLabel, toNumber } from '../../../src/lib/format';
import { useTheme } from '../../../src/theme/theme';
import {
  Badge,
  Body,
  Button,
  Caption,
  Card,
  Chip,
  EmptyState,
  ErrorState,
  Overline,
  PageHeader,
  Row,
  Screen,
  SegmentedControl,
  SkeletonList,
  StatTile,
  Tiny,
  useConfirm,
  useToast,
} from '../../../src/ui';

type StatusFilter = 'ALL' | ReportStatus;

export default function ReportLibraryScreen() {
  const theme = useTheme();
  const router = useRouter();
  const toast = useToast();
  const { confirm } = useConfirm();
  const { hasPermission } = useAuth();

  const [status, setStatus] = useState<StatusFilter>('ALL');
  const [typeFilter, setTypeFilter] = useState<ReportType | 'ALL'>('ALL');
  const [formatFilter, setFormatFilter] = useState<ReportFormat | 'ALL'>('ALL');
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const statistics = useReportStatistics();
  const query = useMemo(
    () => ({
      limit: 30,
      status: status === 'ALL' ? undefined : status,
      type: typeFilter === 'ALL' ? undefined : typeFilter,
      format: formatFilter === 'ALL' ? undefined : formatFilter,
    }),
    [status, typeFilter, formatFilter],
  );
  const reports = useReports(query);
  const remove = useDeleteReport();
  const send = useSendReport();

  const items = reports.data?.items ?? [];
  const canExport = hasPermission('reports:export');

  const download = async (report: Report) => {
    setDownloadingId(report.id);
    const result = await downloadAuthenticatedFile(`/reports/${report.id}/download`, `${report.reference}.${report.format.toLowerCase()}`);
    setDownloadingId(null);
    if (result.saved) toast.success('Download started', `${report.reference}.${report.format.toLowerCase()}`);
    else toast.error('Download failed', result.reason);
  };

  const share = async (report: Report) => {
    const answer = await confirm({
      title: 'Share this report?',
      message:
        'FEMS notifies the inspection services — or the company the report concerns — that the report is ready. It does not email the file.',
      confirmLabel: 'Share',
      requireReason: false,
    });
    if (!answer.confirmed) return;
    try {
      const result = await send.mutateAsync({ id: report.id, payload: {} });
      toast.success('Report shared', `${result.recipients} recipient(s) notified.`);
    } catch (error) {
      toast.error('Could not share', error instanceof ApiError ? error.message : undefined);
    }
  };

  const destroy = async (report: Report) => {
    const answer = await confirm({
      title: 'Delete this report?',
      message: `${report.reference} and its generated file are removed. This is recorded in the audit trail.`,
      confirmLabel: 'Delete',
      destructive: true,
      requireReason: true,
      reasonLabel: 'Why is this report being deleted?',
      reasonMinLength: 10,
    });
    if (!answer.confirmed) return;
    try {
      await remove.mutateAsync(report.id);
      toast.success('Report deleted', report.reference);
    } catch (error) {
      toast.error('Could not delete', error instanceof ApiError ? error.message : undefined);
    }
  };

  const totals = statistics.data;

  return (
    <Screen
      scroll={false}
      refresh={reports.isRefetching ? { refreshing: true, onRefresh: () => reports.refetch() } : undefined}
    >
      <PageHeader
        title="Reports"
        subtitle="Generated from the live register"
        onBack={() => router.back()}
        right={
          hasPermission('reports:create') ? (
            <Button label="New" icon="add-outline" size="sm" onPress={() => router.push('/report/new')} />
          ) : undefined
        }
      />

      {totals ? (
        <Row gap={8} style={{ marginBottom: 12 }}>
          <StatTile label="Reports" value={formatNumber(totals.total)} icon="document-text-outline" />
          <StatTile
            label="Types used"
            value={totals.byType.filter((entry) => entry.generated > 0).length}
            hint={`of ${totals.byType.length} available`}
            icon="albums-outline"
          />
          <StatTile
            label="Size"
            value={`${(toNumber(totals.totalSizeBytes) / 1024 / 1024).toFixed(1)} MB`}
            hint={totals.lastGeneratedAt ? `last ${formatRelative(totals.lastGeneratedAt, 'en')}` : 'nothing generated yet'}
            icon="archive-outline"
          />
        </Row>
      ) : null}

      <SegmentedControl
        value={status}
        options={[
          { value: 'ALL', label: 'All' },
          { value: 'READY', label: 'Ready' },
          { value: 'GENERATING', label: 'Running' },
          { value: 'FAILED', label: 'Failed' },
        ]}
        onChange={setStatus}
      />

      <View style={{ marginVertical: 10, gap: 8 }}>
        {totals ? (
          <View>
            <Overline style={{ marginBottom: 4 }}>Type</Overline>
            <Row gap={6} wrap>
              <Chip label="All types" selected={typeFilter === 'ALL'} onPress={() => setTypeFilter('ALL')} />
              {totals.byType.map((entry) => (
                <Chip
                  key={entry.type}
                  label={`${entry.label}${entry.generated ? ` (${entry.generated})` : ''}`}
                  selected={typeFilter === entry.type}
                  onPress={() => setTypeFilter(entry.type)}
                />
              ))}
            </Row>
          </View>
        ) : null}
        {totals && totals.byFormat.length > 1 ? (
          <Row gap={6} wrap>
            <Tiny tone="faint">Format</Tiny>
            <Chip label="Any" selected={formatFilter === 'ALL'} onPress={() => setFormatFilter('ALL')} />
            {totals.byFormat.map((entry) => (
              <Chip
                key={entry.format}
                label={`${entry.format} (${entry.count})`}
                selected={formatFilter === entry.format}
                onPress={() => setFormatFilter(entry.format)}
              />
            ))}
          </Row>
        ) : null}
      </View>

      {reports.isLoading ? (
        <SkeletonList rows={4} />
      ) : reports.isError ? (
        <ErrorState error={reports.error} onRetry={() => reports.refetch()} />
      ) : items.length === 0 ? (
        <EmptyState
          icon="document-text-outline"
          title="No report matches these filters"
          description="Generate a report to turn the live register into a PDF, CSV or JSON file you can download and share."
          actionLabel={hasPermission('reports:create') ? 'Generate a report' : undefined}
          onAction={() => router.push('/report/new')}
          secondaryLabel={status !== 'ALL' || typeFilter !== 'ALL' ? 'Clear filters' : undefined}
          onSecondary={() => {
            setStatus('ALL');
            setTypeFilter('ALL');
            setFormatFilter('ALL');
          }}
        />
      ) : (
        items.map((report) => (
          <Pressable
            key={report.id}
            onPress={() => router.push({ pathname: '/report/[id]', params: { id: report.id } })}
            accessibilityRole="button"
            accessibilityLabel={`Report ${report.reference}, ${reportTypeLabel(report.type)}`}
            style={({ pressed }) => ({ marginBottom: 10, opacity: pressed ? 0.85 : 1 })}
          >
            <Card>
              <Row justify="space-between" style={{ marginBottom: 6 }}>
                <Overline>{reportTypeLabel(report.type)}</Overline>
                <Badge
                  label={reportStatusLabel(report.status)}
                  tone={report.status === 'READY' ? 'success' : report.status === 'FAILED' ? 'danger' : 'warning'}
                  compact
                />
              </Row>
              <Body style={{ fontWeight: '700' }}>{report.title}</Body>
              <Row gap={8} wrap style={{ marginTop: 6 }}>
                <Badge label={report.format} tone="neutral" compact />
                <Tiny tone="faint">{report.reference}</Tiny>
                {report.forest ? <Tiny tone="faint">· {report.forest.name}</Tiny> : null}
                {report.company ? <Tiny tone="faint">· {report.company.name}</Tiny> : null}
              </Row>
              <Tiny tone="faint" style={{ marginTop: 6 }}>
                {report.generatedAt ? `generated ${formatDateTime(report.generatedAt, 'en')}` : `created ${formatDateTime(report.createdAt, 'en')}`}
                {report.generatedBy ? ` by ${report.generatedBy.firstName} ${report.generatedBy.lastName}` : ''}
                {report.sizeBytes ? ` · ${(toNumber(report.sizeBytes) / 1024).toFixed(0)} KB` : ''}
              </Tiny>
              {report.status === 'FAILED' && report.errorMessage ? (
                <Tiny style={{ color: theme.colors.danger, marginTop: 6 }}>{report.errorMessage}</Tiny>
              ) : null}

              <Row gap={8} style={{ marginTop: 10 }} wrap>
                <Button
                  size="sm"
                  label="Open"
                  variant="secondary"
                  icon="reader-outline"
                  onPress={() => router.push({ pathname: '/report/[id]', params: { id: report.id } })}
                />
                {canExport && report.status === 'READY' ? (
                  <Button
                    size="sm"
                    label="Download"
                    icon="download-outline"
                    loading={downloadingId === report.id}
                    onPress={() => void download(report)}
                  />
                ) : null}
                {canExport && report.status === 'READY' ? (
                  <Button size="sm" label="Share" variant="secondary" icon="share-outline" onPress={() => void share(report)} />
                ) : null}
                {hasPermission('reports:delete') ? (
                  <Button size="sm" label="Delete" variant="danger" icon="trash-outline" onPress={() => void destroy(report)} />
                ) : null}
              </Row>
            </Card>
          </Pressable>
        ))
      )}

      {hasPermission('reports:create') ? (
        <Card style={{ marginTop: 4 }}>
          <Row gap={8}>
            <Ionicons name="information-circle-outline" size={18} color={theme.colors.info} />
            <Caption tone="muted" style={{ flex: 1 }}>
              A report is built from the database when you request it. FEMS keeps the file and its parameters, so a report can always be traced back to the
              data it was generated from.
            </Caption>
          </Row>
        </Card>
      ) : null}
    </Screen>
  );
}
