import { Body, Controller, Delete, Get, Param, Post, Query, Res } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiParam, ApiProduces, ApiTags } from '@nestjs/swagger';
import type { Response } from 'express';
import { ReportsService } from './reports.service';
import { CreateReportDto, ReportQueryDto, SendReportDto } from './dto/report.dto';
import { CurrentUser, RequireAnyPermission, RequirePermissions, type AuthenticatedUser } from '../common/decorators';
import { paginate } from '../common/dto/pagination.dto';

const MIME_BY_FORMAT: Record<string, string> = {
  PDF: 'application/pdf',
  CSV: 'text/csv; charset=utf-8',
  JSON: 'application/json',
};

@ApiTags('reports')
@ApiBearerAuth('bearer')
@Controller('reports')
export class ReportsController {
  constructor(private readonly reports: ReportsService) {}

  @Get()
  @RequireAnyPermission('reports:read', 'reports:read_own')
  @ApiOperation({
    summary: 'List generated reports',
    description: 'A company account only sees the reports generated for it; regulators see everything in their scope.',
  })
  async list(@CurrentUser() user: AuthenticatedUser, @Query() query: ReportQueryDto) {
    const { items, total } = await this.reports.list(user, query);
    return paginate(items, total, query.page, query.limit);
  }

  @Get('catalogue')
  @RequireAnyPermission('reports:read', 'reports:read_own')
  @ApiOperation({ summary: 'Report types available, their columns and supported formats' })
  catalogue() {
    return this.reports.catalogue();
  }

  @Get('statistics')
  @RequireAnyPermission('reports:read', 'reports:read_own')
  @ApiOperation({ summary: 'Reports generated by type, format and status' })
  statistics(@CurrentUser() user: AuthenticatedUser) {
    return this.reports.statistics(user);
  }

  @Post('preview')
  @RequireAnyPermission('reports:read', 'reports:read_own')
  @ApiOperation({
    summary: 'Preview the dataset of a report without generating a file',
    description: 'Returns the summary block, the columns and the first 50 rows, computed with the caller’s own scope.',
  })
  preview(@CurrentUser() user: AuthenticatedUser, @Body() dto: CreateReportDto) {
    return this.reports.preview(user, dto);
  }

  @Post()
  @RequirePermissions('reports:create')
  @ApiOperation({
    summary: 'Generate a report',
    description:
      'Builds the dataset from the live database, renders it as PDF, CSV or JSON, stores the file and returns the report record. ' +
      'A report only becomes READY when its file exists; a failed generation is stored as FAILED with the reason.',
  })
  create(@CurrentUser() user: AuthenticatedUser, @Body() dto: CreateReportDto) {
    return this.reports.create(user, dto);
  }

  @Get(':id')
  @RequireAnyPermission('reports:read', 'reports:read_own')
  @ApiOperation({ summary: 'Report metadata with its summary block and totals' })
  findOne(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) {
    return this.reports.findOne(user, id);
  }

  @Get(':id/download')
  @RequirePermissions('reports:export')
  @ApiProduces('application/pdf', 'text/csv', 'application/json')
  @ApiOperation({ summary: 'Download the generated file' })
  async download(
    @CurrentUser() user: AuthenticatedUser,
    @Param('id') id: string,
    @Res() response: Response,
  ): Promise<void> {
    const { stream, report } = await this.reports.download(user, id);
    const mime = MIME_BY_FORMAT[report.format] ?? 'application/octet-stream';
    const extension = report.format.toLowerCase();
    response.setHeader('Content-Type', mime);
    response.setHeader('Content-Disposition', `attachment; filename="${report.reference}.${extension}"`);
    stream.pipe(response);
  }

  @Post(':id/send')
  @RequirePermissions('reports:export')
  @ApiOperation({
    summary: 'Share a ready report',
    description: 'Notifies the inspection services, or the company (companies) the report concerns, that the report is available.',
  })
  send(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string, @Body() dto: SendReportDto) {
    return this.reports.send(user, id, dto);
  }

  @Delete(':id')
  @RequirePermissions('reports:delete')
  @ApiParam({ name: 'id' })
  @ApiOperation({ summary: 'Delete a report and its file' })
  remove(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) {
    return this.reports.remove(user, id);
  }
}
