import { authProfileFrench } from './catalogue/auth-profile';
import { dashboardPublicFrench } from './catalogue/dashboard-public';
import { transactionsFrench } from './catalogue/transactions';
import { fieldworkFrench } from './catalogue/fieldwork';
import { adminOperationsFrench } from './catalogue/admin-operations';

export type AppLanguage = 'en' | 'fr';

const COMMON_FRENCH: Record<string, string> = {
  'Search': 'Rechercher',
  'Clear search': 'Effacer la recherche',
  'Choose…': 'Choisir…',
  'Close': 'Fermer',
  'Close menu': 'Fermer le menu',
  'Go back': 'Retour',
  'Back': 'Retour',
  'Cancel': 'Annuler',
  'Confirm': 'Confirmer',
  'Try again': 'Réessayer',
  'Loading…': 'Chargement…',
  'Refreshing…': 'Actualisation…',
  'No data in this range.': 'Aucune donnée pour cette période.',
  'No monthly data available.': 'Aucune donnée mensuelle disponible.',
  'No history recorded yet.': 'Aucun historique enregistré pour le moment.',
  'The preview returned no rows for this filter.': 'Aucun résultat pour ce filtre.',
  'No action is available on this record for your role right now.':
    'Aucune action n’est actuellement disponible pour votre rôle sur cet enregistrement.',
  'Not available for your role': 'Non disponible pour votre rôle',
  'You are offline': 'Vous êtes hors ligne',
  'Something went wrong': 'Une erreur est survenue',
  'The request could not be completed. Please try again.':
    'La demande n’a pas pu aboutir. Veuillez réessayer.',
  'Explain the decision — recorded in the audit trail':
    'Expliquez votre décision — elle sera consignée dans le journal d’audit.',
  'Reason': 'Motif',
  'characters minimum': 'caractères minimum',
  'Your position': 'Votre position',
  'Captured by this device': 'Enregistré par cet appareil',
  'FEMS emblem': 'Emblème FEMS',
  'Accuracy': 'Précision',
  'captured by this device': 'capturée par cet appareil',
  'Maximum': 'Maximum',
  'more rows in the generated file': 'lignes supplémentaires dans le fichier généré',
  'Check connection': 'Vérifier la connexion',
  'Working offline': 'Mode hors ligne',
  'Engine': 'Moteur',
  'Annual cut': 'Coupe annuelle',
  'Centred on:': 'Centré sur :',
  'Clear the nearby search': 'Effacer la recherche à proximité',
  'feature(s) within': 'entité(s) dans un rayon de',
  'features ·': 'entités ·',
  'in scope': 'dans le périmètre',
  'km away': 'km de distance',
  'km of your position.': 'km de votre position.',
  'Nothing recorded within': 'Aucun enregistrement dans un rayon de',
  'Approved volume': 'Volume approuvé',
  'Awaiting decision': 'En attente de décision',
  'fee due': 'frais dus',
  'inspections': 'inspections',
  'payments': 'paiements',
  'Search permit number, title or company': 'Rechercher un numéro de permis, un titre ou une entreprise',
  'Active palette:': 'Palette active :',
  'Appearance': 'Apparence',
  'Connected to': 'Connecté à',
  'Edit': 'Modifier',
  'Language': 'Langue',
  'Password': 'Mot de passe',
  'Revoke': 'Révoquer',
  'Save': 'Enregistrer',
  'Security': 'Sécurité',
  'Session': 'Session',
  'Sessions': 'Sessions',
  'Shortcuts': 'Raccourcis',
  'Account': 'Compte',
  'Accounts': 'Comptes',
  'Activities': 'Activités',
  'Alerts raised': 'Alertes déclenchées',
  'Change': 'Modifier',
  'Completed': 'Terminé',
  'Database': 'Base de données',
  'Detector': 'Détecteur',
  'Download file': 'Télécharger le fichier',
  'From': 'À partir de',
  'Generated by': 'Généré par',
  'Latency': 'Latence',
  'Model': 'Modèle',
  'Next maintenance': 'Prochaine maintenance',
  'permit(s)': 'permis',
  'Provider': 'Fournisseur',
  'recorded': 'enregistré',
  'Reports': 'Rapports',
  'Role': 'Rôle',
  'Roles': 'Rôles',
  'Rows': 'Lignes',
  'Rows in scope': 'Lignes dans le périmètre',
  'Scope': 'Périmètre',
  'Share': 'Partager',
  'Size': 'Taille',
  'Totals': 'Totaux',
  'Uptime': 'Durée de fonctionnement',
  'Alert console': 'Console des alertes',
  'All analyses': 'Toutes les analyses',
  'Confidence': 'Niveau de confiance',
  'Distribution': 'Répartition',
  'Duplicates skipped': 'Doublons ignorés',
  'Findings': 'Résultats',
  'Requested by': 'Demandé par',
  'Risk level': 'Niveau de risque',
  'Rules evaluated': 'Règles évaluées',
  'Run': 'Lancer',
  'Warnings': 'Avertissements',
  'Filter': 'Filtrer',
  'Level': 'Niveau',
  'conversation(s) · alerts awaiting review': 'conversation(s) · alertes en attente d’examen',
  'FEMS · Ministry of Forestry and Wildlife · data as of':
    'FEMS · Ministère des Forêts et de la Faune · données au',
  '· due': '· échéance',
  '· captured': '· capturé',
  '· overlaps': '· chevauchements',
  '· harvested': '· récoltés',
  '· detected': '· détecté',
  '· engine': '· moteur',
  '· provider': '· fournisseur',
  '· record': '· enregistrement',
  '· review SLA': '· délai d’examen',
  '· since': '· depuis',
  'Alerts are advisory. A confirmation requires a written reason and, for field verification, a linked inspection — the guardrails reported by the API are':
    'Les alertes sont consultatives. Une confirmation nécessite un motif écrit et, pour une vérification sur le terrain, une inspection associée — les garde-fous signalés par l’API sont :',
  'A payment is only successful once the backend has confirmed it with the provider. Use the payment detail screen to re-verify a pending transaction; the provider’s own status is what is stored.':
    'Un paiement n’est réussi qu’après confirmation par le serveur auprès du prestataire. Depuis le détail du paiement, vérifiez à nouveau toute transaction en attente ; le statut enregistré est celui du prestataire.',
  'A permit only becomes operational when it is approved, the fee is settled and the validity window is open. Exploitation against any other state is refused by the API.':
    'Un permis n’est opérationnel qu’après son approbation, le règlement des frais et le début de sa période de validité. L’API refuse toute exploitation dans un autre état.',
  'of the forests on this page are seeded demonstration records. They are labelled DEMO and their coordinates fall inside Cameroon but they do not replace the official register.':
    'des forêts affichées sur cette page sont des données de démonstration. Elles portent la mention DEMO et leurs coordonnées se trouvent au Cameroun, mais elles ne remplacent pas le registre officiel.',
  'A report is built from the database when you request it. FEMS keeps the file and its parameters, so a report can always be traced back to the data it was generated from.':
    'Le rapport est généré à partir de la base de données à votre demande. FEMS conserve le fichier et ses paramètres afin de pouvoir retrouver les données utilisées.',
  'The API is building the dataset. This screen refreshes itself every few seconds until the file exists.':
    'L’API prépare le jeu de données. Cet écran s’actualise toutes les quelques secondes jusqu’à la création du fichier.',
  'Generate a report to turn the live register into a PDF, CSV or JSON file you can download and share.':
    'Générez un rapport pour convertir le registre à jour en fichier PDF, CSV ou JSON à télécharger et à partager.',
};

const FRENCH_TRANSLATIONS: Record<string, string> = {
  ...authProfileFrench,
  ...dashboardPublicFrench,
  ...transactionsFrench,
  ...fieldworkFrench,
  ...adminOperationsFrench,
  ...COMMON_FRENCH,
};
const PHRASE_TRANSLATIONS = Object.entries(FRENCH_TRANSLATIONS)
  .filter(([source]) => source.length >= 5 && source.includes(' '))
  .sort(([left], [right]) => right.length - left.length);

export function normalizeText(value: string): string {
  return value.trim().replace(/\s+/g, ' ');
}

export function translateAppText(value: string, language: AppLanguage): string {
  if (language !== 'fr') return value;
  const normalized = normalizeText(value);
  const exact = FRENCH_TRANSLATIONS[normalized];
  const translated = exact ?? translatePhrases(value);
  if (translated === value) return value;
  const leading = value.match(/^\s*/)?.[0] ?? '';
  const trailing = value.match(/\s*$/)?.[0] ?? '';
  return exact ? `${leading}${exact}${trailing}` : translated;
}

function translatePhrases(value: string): string {
  let translated = value;
  for (const [source, target] of PHRASE_TRANSLATIONS) {
    let offset = 0;
    while (offset < translated.length) {
      const index = translated.indexOf(source, offset);
      if (index === -1) break;
      const before = index > 0 ? translated[index - 1] : '';
      const afterIndex = index + source.length;
      const after = afterIndex < translated.length ? translated[afterIndex] : '';
      const startsWithWord = /[A-Za-zÀ-ÿ0-9]/.test(source[0]);
      const endsWithWord = /[A-Za-zÀ-ÿ0-9]/.test(source[source.length - 1]);
      const hasWordBoundary =
        (!startsWithWord || !/[A-Za-zÀ-ÿ0-9]/.test(before)) &&
        (!endsWithWord || !/[A-Za-zÀ-ÿ0-9]/.test(after));
      if (hasWordBoundary) {
        translated = `${translated.slice(0, index)}${target}${translated.slice(afterIndex)}`;
        offset = index + target.length;
      } else {
        offset = afterIndex;
      }
    }
  }
  return translated;
}
