ALTER TABLE `ai_analyses`
  MODIFY `provider` ENUM('OPENROUTER', 'GEMINI', 'LOCAL_RULE_ENGINE') NOT NULL DEFAULT 'LOCAL_RULE_ENGINE';

ALTER TABLE `ai_alerts`
  MODIFY `detector` ENUM('OPENROUTER', 'GEMINI', 'LOCAL_RULE_ENGINE') NOT NULL DEFAULT 'LOCAL_RULE_ENGINE';

ALTER TABLE `ai_messages`
  MODIFY `provider` ENUM('OPENROUTER', 'GEMINI', 'LOCAL_RULE_ENGINE') NULL;
